package main

import "fmt"

// renderCIRecipe is the shape a repository starts with when it adopts an ephemeral
// fleet, so that the lessons of 2026-09-05 (DOCS of the kami monorepo: 3 753 jobs at a
// median of six seconds, 29 machines for a one-file pull request of which 20 did under
// thirty seconds of work) are the starting point, not a discovery.
//
// The rules the recipe encodes, each in a comment next to the line that enforces it:
//   - no job under a minute: guards are STEPS of one job; the plan is a step too, not a
//     job of its own (every job is a machine that takes about a minute to create);
//   - a pull request is planned from its MERGE-BASE, never from the base branch's tip
//     (with several people merging, a two-dot diff from main's tip lists their changes
//     as yours and every scope lights up);
//   - every job carries a timeout-minutes, to be set from a measured p95 with a margin;
//   - one gate job, `if: always()`, is the only check branch protection needs; it
//     passes when nothing was affected and fails when a selected job failed. It is the
//     one small job the lint will keep pointing at: keep it the only one.
func renderCIRecipe(options initOptions) string {
	return fmt.Sprintf(`# Generated by "runneryard init --with-workflows". Edit .github/ci-scopes.json to name
# your lanes (a lane = the paths a set of jobs proves); add guards as STEPS of the
# guards job, never as jobs; give every job a timeout measured from its p95.
# Check the shape any time with: runneryard lint-workflows
name: CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

# A newer push to the same branch replaces the run in flight; main keeps every run
# (a deploy that waits for main's proof must never see it cancelled).
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

jobs:
  # One machine for the plan AND the guards: the plan is seconds of git, the guards are
  # seconds of scripts; neither deserves a machine of its own.
  guards:
    runs-on: %q
    timeout-minutes: 10
    outputs:
      affected: ${{ steps.plan.outputs.affected }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Plan from the merge-base
        id: plan
        env:
          EVENT: ${{ github.event_name }}
          BASE: ${{ github.event.pull_request.base.sha || github.event.before }}
          HEAD: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          set -euo pipefail
          # A pull request diffs from the merge-base; a push keeps its exact range.
          if [ "$EVENT" = pull_request ]; then from="$(git merge-base "$BASE" "$HEAD")"; else from="$BASE"; fi
          if [ "$EVENT" = workflow_dispatch ] || ! [[ "$from" =~ ^[0-9a-f]{40}$ ]] || [[ "$from" =~ ^0+$ ]]; then
            echo "affected=$(node -e 'const s=require("./.github/ci-scopes.json");console.log(JSON.stringify(Object.fromEntries(Object.keys(s).map(k=>[k,true]))))')" >> "$GITHUB_OUTPUT"
            echo "no comparable base: every lane runs (fail closed)"; exit 0
          fi
          git diff --name-only --no-renames "$from" "$HEAD" > /tmp/changed.txt
          node -e '
            const fs = require("fs"); const path = require("path");
            const scopes = require("./.github/ci-scopes.json");
            const changed = fs.readFileSync("/tmp/changed.txt", "utf8").split("\n").filter(Boolean);
            const globToRe = g => new RegExp("^" + g.split("**").map(p => p.split("*").map(x => x.replace(/[.+?^${}()|[\]\\]/g, "\\$&")).join("[^/]*")).join(".*") + "$");
            const affected = Object.fromEntries(Object.entries(scopes).map(([lane, globs]) => [lane, globs.some(g => { const re = globToRe(g); return changed.some(f => re.test(f)); })]));
            fs.appendFileSync(process.env.GITHUB_OUTPUT, "affected=" + JSON.stringify(affected) + "\n");
            console.log("changed", changed.length, "files;", JSON.stringify(affected));
          '
      # Guards: one-script checks that read the tree. Add yours as steps here.
      - name: Guards (add yours as steps, never as jobs)
        run: |
          set -euo pipefail
          echo "no guards yet: add steps such as 'node scripts/guard-*.mjs' here"

  # A lane's proof runs only when the plan selected it. Copy this job per lane.
  tests:
    needs: guards
    if: ${{ fromJSON(needs.guards.outputs.affected).app == true }}
    runs-on: %q
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
      - run: echo "run the lane's tests here"

  # The ONE check to require in branch protection. It passes when a lane was not
  # affected (its job was skipped) and fails when a selected job failed. It is the one
  # job of seconds this recipe keeps, because protection needs a job name; keep it so.
  gate:
    needs: [guards, tests]
    if: always()
    runs-on: %q
    timeout-minutes: 2
    steps:
      - name: Every selected job must have succeeded
        env:
          RESULTS: ${{ toJSON(needs) }}
        run: |
          set -euo pipefail
          echo "$RESULTS" | node -e '
            const needs = JSON.parse(require("fs").readFileSync(0, "utf8"));
            const bad = Object.entries(needs).filter(([, v]) => !["success", "skipped"].includes(v.result));
            if (bad.length) { console.error("red:", bad.map(([k, v]) => k + "=" + v.result).join(", ")); process.exit(1); }
            console.log("gate: every selected job succeeded or was not selected");
          '
`, options.scaleSet, options.scaleSet, options.scaleSet)
}

// renderCIScopes is the lane map the plan step reads: lane -> globs. One lane, "app",
// to begin with; the operator names theirs.
func renderCIScopes() string {
	return `{
  "app": ["src/**", "package.json", "pnpm-lock.yaml"]
}
`
}
